### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by viluon** [ebernerd/WaveLite#1]
This project has a lot of potential, and I'd be interested in forking it. There's however [no license](http://choosealicense.com/no-license/) included. Could you please add one?

**Comment by ebernerd** [comment]
We wouldn't mind if you did. We have no license yet because this project is no where near done. We put it here for the sake of the developers being able to make different branches for syncing's sake.

Will let you know when the project is ready for something like that.

**Comment by viluon** [comment]
Thanks for the quick reply @ebernerd, the legal issue with projects without a license is perhaps best summarized by the short article I linked.

> ... generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that **nobody else may reproduce, distribute, or create derivative works from your work.**

If you intend to make this project open source (which I sincerely hope so) I would recommend you going with [the MIT License](http://choosealicense.com/licenses/mit/), which permits use in all kinds of other projects, as long as the original authors are credited appropriately.

There is also a variety of [other open source licenses](http://choosealicense.com/) to choose from. Adding a `LICENSE.md` file to the root of a repository is easy, and GitHub even has a [shortcut](https://github.com/blog/1327-creating-files-on-github) for that. Doing so resolves all the potential legal problems.

Best luck with WaveLite!

**Comment by viluon** [comment]
Thanks guys! :shipit:
